### ISSUE TITLE
ValueError: Cannot feed value of shape (3, 4096) for Tensor 'PartGT:0', which has shape '(3, 4096, 13)'

### ISSUE THREAD

**Issue by mtli77** [alex-xun-xu/WeakSupPointCloudSeg#5]
Hi @alex-xun-xu 
Thank you for sharing this wonderful project!

When I ran the training script on S3DIS, an error was caught as :
```
start training 0-th epoch at Fri Oct  2 21:25:06 2020
2020-10-02 21:25:09.768593: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
Batch 5577 TrainedSamp 16731  mbLoss 0.8798 Avg Acc 75.86%
TrainingSet  Avg Loss 0.7371 Avg Acc 75.86%

start validation 0-th epoch at Fri Oct  2 21:36:45 2020
Traceback (most recent call last):
  File "train_S3DIS.py", line 133, in <module>
    eval_avg_loss, eval_avg_acc, eval_miou = TrainOp.EvalOneEpoch(Loader)
  File "/disk/tia/WeakSupPointCloudSeg/S3DIS/S3DIS_DGCNN_trainer.py", line 376, in EvalOneEpoch
    self.Mask_ph: Mask_bin})
  File "/home/ubuntu/.conda/envs/tia36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ubuntu/.conda/envs/tia36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (3, 4096) for Tensor 'PartGT:0', which has shape '(3, 4096, 13)'
```

Could you help me to solve this problem?
Waiting for your reply!

**Comment by nanwang-mindtrace** [comment]
Hi @Violetit
I'm having the same error. Have you solved this problem?

**Comment by zwy1996** [comment]
Hi,
I have fix the error, you may run the code using the default parameters. If you set the "Style=full" in the "train_S3DIS.py", you can run the code normally.
